---
title: "[IPO6] Prepare and check other scales"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE, echo=F}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

<br>
<br>

```{r, echo=T, eval=T}
df <- read.csv(file="./data/df_final.csv")
dim(df) 
```

181 rows and 585 (created an extra ID (="X") variable).

``` {r, echo=T, eval=T}

# A bit of tidying. 
library(plyr)
df <- plyr::rename(df, c("X"="id"))

df_names <- colnames(df)
for(i in df_names) {
  df[[i]] <- as.numeric(df[[i]])
  }

df$gender <- as.factor(df$gender)
df$education <- as.factor(df$education)
df$lca_class <- as.factor(df$lca_class)
```

<br>
<br>

## Get the databases separately for each instrument 
```{r, eval=T, echo=T}
df_staxi <- df[grep("^STAX", names(df), value=T)]
df_des <- df[grep("^DES", names(df), value=T)]
df_scl <- df[grep("^SCL", names(df), value=T)]
df_axis1_dg <- df[grep("^S1DG[1-9]$|S1DG10|S1DG11|
                      |S1DG12|S1DG13|S1DG16|S1DG17|S1DG18|S1DG19|S1DG20|S1DG21|S1DG22|
                       |S1DG25|S1DG26|S1DG27|S1DG28|S1DG29|S1DG30|S1DG31|S1DG32|S1DG33|
                       |S1DG40|S1DG41|S1DG42|S1DG43|S1DG44|S1DG45|S1DG46|S1DG47|S1DG49|
                       |S1DG53|S1DG54", names(df), value=T)]
df_axis2_dg <- data.frame(df[grep("S7_32|S15_41|S24_50|S32_58|S40_66|S48_74|
                       |S59_84SZ|S65_92|S72_101|S89_111|S104_121|S119_139", names(df), value=T)])
df_axis2_sever <- data.frame(df[grep(
                              "S1_25|S2_26|S3_27|S4_28|S5_29|S6_30|S7_31|S8_33|S9_34|
                              |S10_35|S11_36|S12_37|S13_38|S14_39|S16_42|S17_43|
                              |S18_44|S19_45|S20_46|S21_47|S22_48|S23_49|^S24|S25_51|
                              |^S26|S27_52|S28_53|S29_54|S30_55|S31_56|S32_57|S33_59|
                              |S34_60|S35_61|S36_62|S37_63|S38|S39_64|S40_65|S41_67|
                              |S42_68|S43_69|S44_70|S45_71|S46|S47_72|S48_72|S49_75|
                              |S50|S51|S52_76|S53|S54|S55_77|S56|S57|S57_78|S57_79|S57_80|
                              |S57_81|S58_82|S59_84$|S60_85|S61_86|S62_87|S63_88|
                              |S63_89|S64_90|S65_91|S66_93|S67_94|S68_95|S69_96|S69_97|
                              |S70_98|S71_99|S72_100|S73_102|S74|S75_103|S76|S77_104|
                              |S78|S79_105|S80_106|S81_107|S82|S83|S84|S85_108|S86|S87_109|
                              |S88|S89_110|S90_112|S91_113|S92_114|S93|S94|S95|
                              |S96_115|S97_116|S98|S99_117|S100_118|S101_119|S102|S103|
                              |S104_120|S105_122|S105_123|S106_124|S107_125|S108_126|
                              |S110_128|S111_129|S112_130|S113_131|S114_132|S115_133|
                              |S116_134|S117_135|S118_136|S119_137|S119_138|S119_139", 
                            names(df), value=T
                              )])
```

<br>
<br>

## Prepare the scales 
```{r, eval=T, echo=T}
library(psych)
scl.keys <- make.keys(df_scl, list(
  som = c(1, 12, 27, 4, 40, 42, 48, 49, 52, 53, 56, 58), # Somatization
  ocd = c(10, 28, 3, 38, 45, 46, 51, 55, 65, 9), # Obsession
  hos = c(11, 24, 63, 67, 74), # Hostility
  pho = c(13, 25, 47, 50, 70, 75, 82), # Phobic Anxiety
  dep = c(14, 15, 20, 22, 26, 29, 30, 31, 32, 5, 54, 71, 79), # Depression
  psy = c(16, 35, 62, 7, 77, 84, 85, 87, 88, 90), # Psychoticism
  anx = c(17, 2, 23, 33, 39, 57, 72, 78, 80, 86), # Anxiety
  par = c(18, 43, 68, 76, 8, 83), # Paranoia
  int = c(21, 34, 36, 37, 41, 6, 61, 69, 73), # Interpersonal Sensitivity
  SUM = c(1:90)
  ))

staxi.keys <- make.keys(df_staxi, list(  
  state = c(1:25), # State Anger
  expr = c(26:57), # Anger expression and anger control
  ang_fe = c(1, 2, 3, 6, 10), # Feeling of anger
  ang_ve = c(4, 9, 12, 13, 15), # Verbal expression of anger
  ang_ph = c(5, 7, 8, 11, 14), # Bodily (physical) expression of anger
  ang_te = c(16, 17, 18, 21), # Angry temperament
  ang_re = c(19, 20, 23, 25), # Anger reaction
  ang_expr = c(27, 31, 35, 39, 43, 47, 51, 55), # Expression of anger 
  ang_rep = c(29, 33, 37, 41, 45, 49, 53, 57), # Repression of anger
  ang_expr_ctrl = c(26, 30, 34, 38, 42, 46, 50, 54), # Controlling the expression of anger
  ang_rep_ctrl = c(28, 32, 36, 40, 44, 48, 52, 56) # Controlling the repression of anger
  ))

des.keys <- make.keys(df_des, list(
  amn = c(3, 4, 5, 6, 8, 10, 25, 26), # Amnesia
  abs = c(2, 14, 15, 16, 17, 18, 20, 22, 23), # Absorption in imagination
  depers = c(7, 11, 12, 13, 27, 28) # Depersonalisation-derealisation
  ))

axis1_dg.keys <- make.keys(df_axis1_dg, list(
  axis1_dg_sum = c(1:40)
  ))

# df_axis1_dg$S1DG29  # there were no transsexual participants in this sample so this item was removed
# df_axis1_dg$S1DG25
# df_axis1_dg$S1DG20
# df_axis1_dg$S1DG21
# df_axis1_dg$S1DG30
# df_axis1_dg$S1DG33
## all of the above items were excluded because there were no such diagnoses (all of them were items to detect psychotic symptoms)

axis1_catego.keys <- make.keys(df_axis1_dg, list(
  anx = c("S1DG8", "S1DG9", "S1DG10", "S1DG11", "S1DG12", "S1DG16", 
          "S1DG22", "S1DG41", "S1DG54"),
  obs = c("S1DG5"), 
  depr = c("S1DG4", "S1DG43"), 
  bipol = c("S1DG31", "S1DG27", "S1DG28"), 
  # psych = c("S1DG25", "S1DG20", "S1DG21", "S1DG30", "S1DG33"), 
  somatof = c("S1DG17", "S1DG45", "S1DG46"), 
  dissoc = c("S1DG18"), 
  sud = c("S1DG7", "S1DG32", "S1DG40", "S1DG42", "S1DG44", "S1DG53"), 
  ED_imp = c("S1DG2", "S1DG3", "S1DG13"), 
  ED_rest = c("S1DG1") 
  # gend_id = c("S1DG29")
  ))
  
## let's recode the diagnoses so that only 3=positive, 2 and 1 == negative diagnosis
axis2_dg_names <- names(df_axis2_dg)
for(i in axis2_dg_names) {
  df_axis2_dg[[i]][df_axis2_dg[[i]] == "1"] <- "0"
  df_axis2_dg[[i]][df_axis2_dg[[i]] == "2"] <- "0"
  df_axis2_dg[[i]][df_axis2_dg[[i]] == "3"] <- "1"
  }

for(i in axis2_dg_names) {
  df_axis2_dg[[i]] <- as.numeric(df_axis2_dg[[i]])
  }

axis2_dg.keys <- make.keys(df_axis2_dg, list(
  axis2_dg_sum = c(1:12)
  ))

## we also need the information how many personality disorder symptoms were actually positive (= severe). 
## so we'll need to record these in the following way: 3=positive (1), 2 and 1 = negative (0) symptom
axis2_sever_names <- colnames(df_axis2_sever)
for(i in axis2_sever_names) {
  df_axis2_sever[[i]][df_axis2_sever[[i]] == "1"] <- "0"
  df_axis2_sever[[i]][df_axis2_sever[[i]] == "2"] <- "0"
  df_axis2_sever[[i]][df_axis2_sever[[i]] == "3"] <- "1"
  }

for(i in axis2_sever_names) {
  df_axis2_sever[[i]] <- as.numeric(df_axis2_sever[[i]])
  }

axis2_sever.keys <- make.keys(df_axis2_sever, list(
  axis2_sever_sum = c(1:127)
  ))
```

<br>
<br>

## Finally, let's calculate the scales 
```{r, eval=T, echo=T, message=F, warning=F}
SCL_scores <- scoreItems(scl.keys, df_scl, totals=F, missing=TRUE, impute="median")
STAXI_scores <- scoreItems(staxi.keys, df_staxi, totals=F, missing=TRUE, impute="median") 
DES_scores <- scoreItems(des.keys, df_des, totals=F, missing=TRUE, impute="median")
axis1_dg_scores <- scoreItems(axis1_dg.keys, df_axis1_dg, totals=F, missing=T, impute="median")
axis1_dg_scores_total <- scoreItems(axis1_dg.keys, df_axis1_dg, totals=T, missing=T, impute="median")
axis1_catego <- scoreItems(axis1_catego.keys, df_axis1_dg, totals=F, missing=T, impute="median")
axis1_catego_total <- scoreItems(axis1_catego.keys, df_axis1_dg, totals=T, missing=T, impute="median")
axis2_dg_scores <- scoreItems(axis2_dg.keys, df_axis2_dg, totals=T)
axis2_sever_scores <- scoreItems(axis2_sever.keys, df_axis2_sever, totals=T, missing=T, impute="median")
# note that S111_129 had no variance (no positive cases in this sample) so was deleted from keys. 
```




